### ISSUE TITLE
Receiving 0.00 from `object1_temperature` and `ambient_temperature` but `raw_ir_channel1` returns detected IR

### ISSUE THREAD

**Issue by mjhouse** [eldruin/mlx9061x-rs#3]
HAL: avr-hal
System: Arduino Nano (atmega328p)

I'm doing this:
```
    let a4 = pins.a4.into_pull_up_input(&mut pins.ddr);
    let a5 = pins.a5.into_pull_up_input(&mut pins.ddr);

    let i2c = I2cMaster::new(
        dp.TWI,
        a4, 
        a5,
        57600
    );

    let addr = SlaveAddr::default();
    let mut sensor = Mlx9061x::new_mlx90614(i2c, addr, 5).unwrap();

    loop {
        let temp = sensor.object1_temperature().unwrap();
        println!("Object temperature: {}ºC", temp);
        ...
    }
```

Which returns:

```
Object temperature: 0.00ºC
Object temperature: 0.00ºC
...
```
IR data seems to vary a lot more. The same setup, but printing `raw_ir_channel1` outputs values like this:

```
34
34
32771
12
35
32770
25
64
54
...
```

If there's something obvious that I'm missing, let me know.

**Comment by eldruin** [comment]
I do not immediately know what the problem is. Since you can obviously read the RAW_IR register, the communication should be working fine.
I suppose there is some misconfiguration in the `ConfigRegister1` so that the device is not producing results in the `TOBJ1` / `TA` registers.
I would advise you to read the value of that register and compare it with the datasheet to figure out what is wrong.
Reading/Changing this register is not directly supported by this driver at the moment.

**Comment by antonio-hickey** [comment]
hey @mjhouse how did you get f32 to print? I'm also using a arduino board, but I can't print out floats. I looked through your github but couldn't find any code related to this. Would love to see your source code for this even if you never finished it, thanks.

email: antonio.f.hickey@gmail.com

**Comment by mjhouse** [comment]
> hey @mjhouse how did you get f32 to print? I'm also using a arduino board, but I can't print out floats. I looked through your github but couldn't find any code related to this. Would love to see your source code for this even if you never finished it, thanks.
> 
> email: [antonio.f.hickey@gmail.com](mailto:antonio.f.hickey@gmail.com)

I honestly have no idea, man. I forgot I even made this issue.

**Comment by antonio-hickey** [comment]
> > hey @mjhouse how did you get f32 to print? I'm also using a arduino board, but I can't print out floats. I looked through your github but couldn't find any code related to this. Would love to see your source code for this even if you never finished it, thanks.
> > email: [antonio.f.hickey@gmail.com](mailto:antonio.f.hickey@gmail.com)
> 
> I honestly have no idea, man. I forgot I even made this issue.

All good bro thanks for the reply, I just ended up rewriting this crate to use `u16` instead of `f32` bc it was easier than trying to work with floats on bare metal.

**Comment by mjhouse** [comment]
Yeah, they really aren't built for that
